#!/usr/bin/env python3
"""Compatibility entry point for the manuscript simulation sweep.

The paper's simulation table is generated by ``phase_ls_research_sweep.py``.
This filename previously held an older Phase-LS-only benchmark with different
defaults and estimators; it now delegates to the manuscript sweep so the repo
has one reproducible source of truth for the synthetic results.
"""

from __future__ import annotations

from phase_ls_research_sweep import main


if __name__ == "__main__":
    main()
